# Generated by Django 3.1.7 on 2021-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what2eat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='published',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredient',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='food',
            name='picture',
            field=models.CharField(default='', max_length=100),
        ),
    ]
