# Generated by Django 3.1.7 on 2021-04-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what2eat', '0002_auto_20210404_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='picture',
            new_name='link',
        ),
        migrations.AddField(
            model_name='food',
            name='methods',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='food',
            name='thumbnail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
