# Generated by Django 3.1.7 on 2021-04-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what2eat', '0004_foodratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodratings',
            old_name='foodid',
            new_name='food',
        ),
    ]
