# Generated by Django 3.1.7 on 2021-04-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what2eat', '0005_auto_20210411_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodratings',
            old_name='food',
            new_name='fooditem',
        ),
    ]
