# Generated by Django 3.1.7 on 2021-05-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('what2eat', '0006_auto_20210411_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('recipe_name', models.TextField(default='')),
                ('image_url', models.TextField(default='')),
                ('ingredients', models.TextField(default='')),
                ('methods', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='foodratings',
            name='fooditem',
        ),
        migrations.RemoveField(
            model_name='foodratings',
            name='userid',
        ),
        migrations.AddField(
            model_name='foodratings',
            name='fooditem_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodratings',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('ratings', models.IntegerField(default=0)),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='what2eat.food')),
            ],
        ),
    ]
