# Generated by Django 3.1.7 on 2021-05-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what2eat', '0007_auto_20210501_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
        migrations.RemoveField(
            model_name='food',
            name='link',
        ),
        migrations.RemoveField(
            model_name='food',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='food',
            name='title',
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='food',
            name='recipe_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='recipe_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='methods',
            field=models.TextField(default=''),
        ),
    ]
