# Generated by Django 3.1.7 on 2021-05-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what2eat', '0008_auto_20210501_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='recipe_id',
        ),
    ]
